# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ECE532/Lab_and_Project/532_pmod_camera_dist_new_version_2017/532_pmod_camera_dist/src/ip/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ECE532/Lab_and_Project/532_pmod_camera_dist_new_version_2017/532_pmod_camera_dist/src/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/ECE532/Lab_and_Project/532_pmod_camera_dist_new_version_2017/532_pmod_camera_dist/src/ip/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ECE532/Lab_and_Project/532_pmod_camera_dist_new_version_2017/532_pmod_camera_dist/src/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
